DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEE (
  ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
  UUID VARCHAR(36) NOT NULL,
  CPF VARCHAR(11) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PHONE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  AGE INTEGER,
  DEPARTMENT_ID INTEGER,
  CONSTRAINT FK_Department FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT(ID)
);